export const BACKEND_MOMENT_DATE_FORMAT = "YYYY-MM-DD";
export const FRONTEND_MOMENT_DATE_FORMAT = "DD.MM.YYYY";
export const BACKEND_MOMENT_DATE_FORMAT1 = "YYYY-MM-DD HH:mm";
export const FRONTEND_MOMENT_DATE_FORMAT1 = "DD.MM.YYYY HH:mm";
